language: cpp

before_install:
   - uname -a
   - cat /etc/issue
   - pwd
   - apt-get -qq -y install binfmt-support bison build-essential ccache debootstrap flex gawk gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf gettext linux-headers-generic linux-image-generic lvm2 qemu-user-static texinfo texlive u-boot-tools uuid-dev zlib1g-dev unzip libncurses5-dev pkg-config libusb-1.0-0-dev

before_script:
   - pwd

script:
   - sudo ./build.sh

after_script:
   - echo "done"

notifications:
   email:
      - kaplan2539@gmail.com
   on_success: change
   on_failure: always
