language: cpp
before_install: 
before_script:
- pwd
script:
- sudo ./build.sh
after_script:
- echo "done"
notifications:
  email:
  - kaplan2539@gmail.com
  on_success: change
  on_failure: always

before_deploy:
  - pwd
  - ls -ltra
  - git fetch --tags
  - sudo chown travis:travis artifact.txt

deploy:
  provider: releases
  api_key:
    secure: hcNm8lVfoi9t1UjZsPeBVqO6ckfAhWQkpGKRj/K0VepFvODBpgVBdHwpLdkd9GL7VMxW4vAAz2olksmXj6m0lyCIgj0/+UR59pjoS5lZRvxuQ34dQnx5YXvgkkA4nSlyoi716C+UR0guEmK8Qecu3FT8Vt1Z/8DwXAzsb3EOj+g=
  file: ~/cubie/ct-ubuntu/output/ct-ubuntu.raw
  skip_cleanup: true
  on:
    repo: kaplan2539/Cubietruck-Ubuntu
    tags: true
    all_branches: true
